name: Bug Report
description: Report a problem with gh-actions-tool-kit
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue!
        Please fill out the details below to help us debug effectively.

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `pip show gh-actions-tool-kit` or check pyproject version.
      placeholder: "e.g., 0.1.0"

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the problem clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the exact commands or workflow steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or workflow output
      render: bash
