name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you’d like to see.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this feature address?
      placeholder: "When using the library, I found that..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution or API
      placeholder: "Add a function like ... that would ..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: textarea
    id: extra
    attributes:
      label: Additional context
